#pragma once

#define DEPTH_LIMIT -1

#define ENABLE_MEAN 1

#define PLAYER_ONE_MEAN 1
#define PLAYER_ONE_MEAN_IMMEDIATE 0
#define PLAYER_ONE_POP_MIRROR 1
#define PLAYER_ONE_MEAN_COUNT_LIMIT -1
#define PLAYER_ONE_MEAN_DEPTH_LOWER_LIMIT -1
#define PLAYER_ONE_MEAN_DEPTH_UPPER_LIMIT -1